name: Deploy to Testnet

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Foundry Deploy Action
        uses: grossiwm/foundry-deploy-action@latest
        with:
          rpc-url: ${{ secrets.TESTNET_RPC_URL }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          chain-id: ${{ secrets.TESTNET_CHAIN_ID }}
          etherscan-api-key: ${{ secrets.ETHERSCAN_API_KEY }}
          deploy-script: script/deploy.s.sol:CounterScript
          project_dir: ./smartcontracts
